# Generated by Django 4.2.3 on 2023-07-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdriver',
            name='profile_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
