# Generated by Django 4.2.3 on 2023-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdriver',
            name='birth',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
