# Generated by Django 4.2.3 on 2023-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_customdriver_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customdriver',
            old_name='is_running',
            new_name='is_able',
        ),
        migrations.AddField(
            model_name='customdriver',
            name='car_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
