# Generated by Django 4.2.3 on 2023-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdriver',
            name='contents',
            field=models.TextField(blank=True, help_text='신고 내용을 작성해주세요.'),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='contents',
            field=models.TextField(blank=True, help_text='신고 내용을 작성해주세요.'),
        ),
    ]
