# Generated by Django 4.2.3 on 2023-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='status',
            field=models.CharField(choices=[('waiting', '배정중'), ('success', '배정완료'), ('riding', '탑승완료'), ('failed', '배정실패'), ('finish', '운행종료'), ('cancel', '취소')], default='waiting', max_length=10),
        ),
    ]
