# Generated by Django 4.2.3 on 2023-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='장소 상세설명'),
        ),
    ]
